//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hand2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class item
    {[Required]
        [Display(Name = "קוד פריט")]
        public int ItemID { get; set; }
        [MinLength(3)]
        [Display(Name = "תאור")]
        public string Description { get; set; }

        [Display(Name = "מחיר")]
        public Nullable<decimal> price { get; set; }

        [Display(Name = "תאריך")]
        public Nullable<System.DateTime> date { get; set; }

        [Display(Name = "תמונה")]
        public string picture { get; set; }
        [Required]
        [Display(Name = "קוד קטגוריה")]
        public Nullable<int> CategoryID { get; set; }
        [Required]
        [Display(Name = "קוד אזור")]
        public Nullable<int> AreaID { get; set; }
        [Required]
        [Display(Name = "קוד משתמש")]
        public Nullable<int> userID { get; set; }

        [Display(Name = "קוד חברה")]
        public string Company { get; set; }

        [Display(Name = "סטטוס")]
        public Nullable<int> status { get; set; }

   
        public virtual Area Area { get; set; }
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
